# Site settings
title: Compomics Docs
email: iain.buchanan@ugent.be
description: > # this means to ignore newlines until "baseurl:"
 Welcome to the website for software projects created and maintained by the Computational Omics and 
 Systems Biology Group. Below you can find a list of software we have developed, and on the subsequent 
 pages are documentation and links to downloads and source code (hosted on our Github page).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://compomics.github.io" # the base hostname & protocol for your site
twitter_username: compomics
github_username:  compomics

exclude: ["generate-docs.py", "README.md", "Gemfile", "Gemfile.lock"]

# Build settings
markdown: kramdown
kramdown:
  input: GFM

defaults:
  -
    scope:
      type: projects
    values:
      layout: "default"
      page_type: project

collections:
  projects:
    output: true
    output_ext: html
    permalink: /projects/:path.html